### ISSUE TITLE
Cookbooks Module - Learners do not Want to Read Documentation in Courses

### ISSUE THREAD

**Issue by burtlo** [chef-training/chef-essentials#140]
> Again, asking people to "read the docs". Seriously? People do not come on a course to be told this. In fact many come on the course because they don't want to wade through all the documentation.

**Comment by mattstratton** [comment]
Used appropriately, I like the use of docs.chef.io when using a resource for the first time. Most resources have lots and lots of attributes and actions that nobody is ever going to "learn"...one of the essential things to get on the habit of when writing basic cookbooks is how to get the "muscle memory" of finding resources and how they work. Otherwise everything looks like the five resources you learned in training :)
