### ISSUE TITLE
Chef Cookbook Module

### ISSUE THREAD

**Issue by ehaselwanter** [chef-training/chef-essentials#154]
in version 1.0.4 p. 3-33/34 is a missed opportunity to introduce chef-client in local mode. or the other way around: why talk about cookbooks but still use chef-apply which is just recipe based. anyhow: I miss some motivation on on why we introduce the cookbook concept but do not really do something with it.

**Comment by burtlo** [comment]
When an initial flow of the content was displayed to me it did transition over to using `chef-client` in the same section as the introduction to using cookbooks.

I personally chose to not to include that transition because I felt like the learner had to be taught quite a bit more:

* moving cookbook into cookbooks directory
* understanding the chef-client command
* understanding the concept of a run list

I thought that the next section made a good transition as well as providing an exercise that emphasized the nature of the run list.

@ehaselwanter in the coming weeks I am going to prepare a more accelerated Essentials content path. In that we will not be using `chef-apply` at all.

**Comment by ehaselwanter** [comment]
ok. I can live with that. or rather: I think it is a good idea to do so. I asked for feedback and got back that `chef-apply` does not really bring any real value in the training. Is there a real use case for it we could come up with?

**Comment by burtlo** [comment]
@ehaselwanter I usually tell learners that `chef-apply` helped us got us feedback sooner. We did not need to generate all the things that I mentioned above. So I ask them to think about situations that they might want that kind of ease to get feedback.

The one situation that I often recommend is when exploring a new platform or platform version. Having the ability to quickly apply resources through the command-line or recipe file (without the cookbook) can give you quick feedback.

**Comment by burtlo** [comment]
See #170 to see the removal of `chef-apply` and the creation of the 'cookbooks' directory before the error occurs.

**Comment by ehaselwanter** [comment]
I think we can close this one now. re-open if you need to.
